### ISSUE TITLE
Are those donation addresses accurate?

### ISSUE THREAD

**Issue by emergent-reasons** [PayButton/paybutton.github.io#1]
I'm hyped.

**Comment by emergent-reasons** [comment]
Thanks! Button works. Let's see if this works too:

@GitCash 0.005 bch for @Soupernerd

**Comment by emergent-reasons** [comment]
Let's try that again.

@GitCash 0.005 bch for @Soupernerd

**Comment by GitCash** [comment]
Hey **Soupernerd**, user **emergent-reasons** tipped you **5000 bits** in Bitcoin Cash ( ~ **$0.48** ).

*[Click here to claim it!](https://gitcash.io/claim/Soupernerd)*

You can also add the "thumbs down" reaction to **emergent-reasons**'s comment above to prevent future tips.
